---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
bird_data <- read_csv(here::here("clean_data/bird_data.csv"))
```


Which bird had the most individual sightings?

```{r}
bird_data %>% 
  group_by(species_common_name, 
           species_scientific_name, 
           species_abbreviation) %>% 
  summarise(individual_sightings = n()) %>% 
  ungroup() %>% 
  slice_max(individual_sightings, n = 1)
```


Which bird had the highest total count?

```{r}
bird_data %>% 
  group_by(species_common_name,
           species_scientific_name,
           species_abbreviation) %>% 
  summarise(total_count = sum(count, na.rm = TRUE)) %>% 
  ungroup() %>% 
  slice_max(total_count, n = 1)
```


Which bird had the highest total count above a latitude of -30?

```{r}
bird_data %>% 
  filter(lat > -30) %>% 
  group_by(species_common_name,
           species_scientific_name,
           species_abbreviation) %>% 
  summarise(total_count = n()) %>% 
  ungroup() %>% 
  slice_max(total_count, n = 1)
```


How many different types of birds were only ever seen in groups of 1?

```{r}
bird_data %>%
  filter(!is.na(count)) %>% 
  group_by(species_common_name,
           species_scientific_name,
           species_abbreviation) %>% 
  mutate(seen_once_test = if_else(count != 1, NA_real_, count)) %>% 
  summarise(count = sum(seen_once_test)) %>% 
  filter(!is.na(count)) %>% 
  ungroup() %>% 
  summarise(num_birds = n())
```


How many penguins were seen? (Hint: there are many types of penguin)

```{r}
bird_data %>% 
  filter(str_detect(species_common_name, "penguin")) %>% 
  summarise(total_count = sum(count, na.rm = TRUE))
```
